version: '3.8'

services:
  a2a-mcp-server:
    build: .
    container_name: a2a-agents
    ports:
      - "${PORT:-8787}:8787"
      - "8800-8850:8800-8850"  # Agent MCP servers
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-100}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-50000}
      - ENABLE_STREAMING=${ENABLE_STREAMING:-true}
      - STREAM_PORT=8787
      - STREAM_HOST=0.0.0.0
      - METRICS_PORT=${METRICS_PORT:-8787}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8787/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - agent_data:/app/data
      - ./data/agent-memory:/app/data/agent-memory:rw
      - ./data/vector_db:/app/data/vector_db:rw
    networks:
      - agent_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: a2a-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - agent_network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: a2a-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=agents123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - agent_network
    profiles:
      - monitoring

volumes:
  agent_data:
  prometheus_data:
  grafana_data:

networks:
  agent_network:
    driver: bridge