global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'a2a-mcp'
    environment: 'production'

scrape_configs:
  # A2A MCP Server metrics
  - job_name: 'a2a-mcp-server'
    static_configs:
      - targets: ['a2a-mcp-server:3000']
        labels:
          service: 'a2a-mcp'
          component: 'server'
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules
rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
