[build]
builder = "dockerfile"

[deploy]
startCommand = "node --max-old-space-size=1024 dist/index.js"
restartPolicyType = "always"

[[services]]
name = "a2a-mcp-server"

[services.variables]
NODE_ENV = "production"
MAX_CONCURRENCY = "50"
MAX_QUEUE_SIZE = "25000"
ENABLE_STREAMING = "true"
STREAM_PORT = "8787"
LOG_LEVEL = "info"
PORT = "8787"

[services.resources]
memory = 1024
cpu = 1000

[services.healthcheck]
path = "/healthz"
port = 8787