# Railway Configuration for A2A MCP Server
#
# This is a base configuration. For two-service deployment:
# - Use railway-ws.json for WebSocket service
# - Use railway-api.json for API/health service
#
# See RAILWAY_SETUP.md for complete deployment guide

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
