# Prometheus Configuration for A2A MCP Server

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'a2a-monitor'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # A2A MCP Server metrics
  - job_name: 'a2a-mcp-server'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['a2a-mcp-server:8787']
        labels:
          service: 'a2a-mcp-server'
          environment: 'production'

  # Node exporter (if installed for system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker metrics (if cAdvisor is running)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
