# Hadolint configuration for Docker linting
# Relaxed rules for development environment

ignored:
  # Allow not pinning package versions in development
  - DL3008  # Pin versions in apt get install
  - DL3009  # Delete the apt-get lists after installing something
  - DL3015  # Avoid additional packages by specifying `--no-install-recommends`
  - DL3016  # Pin versions in npm
  - DL3018  # Pin versions in apk add
  - DL3019  # Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*`
  - DL3027  # Do not use apt as it is meant to be an end-user tool
  - DL4006  # Set the SHELL option -o pipefail before RUN with a pipe in

# Override severity levels
severity:
  # Treat these as warnings instead of errors in dev
  - error: DL3003  # Use WORKDIR to switch to a directory
  - warning: DL3020  # Use COPY instead of ADD for files and folders

# Trusted registries (optional)
trustedRegistries:
  - docker.io
  - gcr.io
  - quay.io
  - registry.hub.docker.com

# Allow specific base images
allowedBaseImages:
  - scratch
  - alpine
  - ubuntu
  - debian
  - node
  - python
  - nginx
  - redis
