# Continue.dev Provider Configurations

providers:
  anthropic:
    apiKeyEnv: ANTHROPIC_API_KEY
    defaultModel: claude-3-5-sonnet-20241022
    models:
      - claude-3-5-sonnet-20241022
      - claude-3-opus-20240229
      - claude-3-haiku-20240307
    options:
      temperature: 0.2
      top_p: 0.9
      maxOutputTokens: 8192

  openai:
    apiKeyEnv: OPENAI_API_KEY
    defaultModel: gpt-4-turbo-preview
    models:
      - gpt-4-turbo-preview
      - gpt-4
      - gpt-3.5-turbo
    options:
      temperature: 0.2
      maxTokens: 4096

  gemini:
    apiKeyEnv: GOOGLE_API_KEY
    defaultModel: gemini-1.5-pro-latest
    models:
      - gemini-1.5-pro-latest
      - gemini-1.5-flash-latest
    options:
      temperature: 0.2
      topK: 40

  deepseek:
    apiKeyEnv: DEEPSEEK_API_KEY
    apiBase: https://api.deepseek.com
    defaultModel: deepseek-chat
    models:
      - deepseek-chat
      - deepseek-coder
    options:
      temperature: 0.2
      maxTokens: 4096

  mistral:
    apiKeyEnv: MISTRAL_API_KEY
    defaultModel: mistral-large-latest
    models:
      - mistral-large-latest
      - mistral-medium-latest
      - codestral-latest
    options:
      temperature: 0.2
      top_p: 0.9

  ollama:
    apiBase: http://localhost:11434
    defaultModel: mistral:7b
    models:
      - mistral:7b
      - codellama:13b
      - deepseek-coder:6.7b
    options:
      temperature: 0.2
      num_ctx: 8192

embeddings:
  openai:
    apiKeyEnv: OPENAI_API_KEY
    model: text-embedding-3-small
    dimensions: 1536

rerank:
  cohere:
    apiKeyEnv: COHERE_API_KEY
    model: rerank-english-v3.0

routing:
  - name: quick
    description: Fast responses for simple queries
    provider: anthropic
    model: claude-3-haiku-20240307
    match:
      - type: token_estimate
        lt: 2000
  - name: powerful
    description: Complex reasoning and large context
    provider: anthropic
    model: claude-3-opus-20240229
    match:
      - type: token_estimate
        gte: 2000
  - name: coder
    description: Code-focused tasks
    provider: deepseek
    model: deepseek-coder
    match:
      - type: intent
        equals: code

safety:
  maxOutputTokens: 8192
  stopSequences: []
  redact:
    - api_key
    - password
    - secret

defaults:
  temperature: 0.2
  systemPrompt: |
    You are Continue.dev integrated assistant. Follow project conventions and autonomous rules.
    Prefer concise, correct outputs. Ask only when uncertainty risks breaking changes.
