name: Copilot Autonomous PR Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  autonomous-review:
    name: Autonomous Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = context.payload.pull_request?.number ||
                             context.payload.inputs?.pr_number;
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            core.setOutput('pr_number', pr_number);
            core.setOutput('title', pr.title);
            core.setOutput('author', pr.user.login);
            core.setOutput('files_changed', files.length);
            core.setOutput('additions', pr.additions);
            core.setOutput('deletions', pr.deletions);
            return { pr, files };

      - name: Analyze code changes
