name: Integration Tests

on:
  push:
    branches: [ main, develop, 'copilot/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run WebSocket integration tests
        run: npm run test:integration:websocket
        continue-on-error: false

      - name: Run MCP monitoring tests
        run: npm run test:integration:monitoring
        continue-on-error: false

      - name: Run load tests
        run: npm run test:integration:load
        continue-on-error: false

      - name: Run end-to-end tests
        run: npm run test:integration:e2e
        continue-on-error: false

      - name: Run all integration tests
        run: npm run test:integration
        continue-on-error: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: |
            test-results/
            *.log

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: integration-tests
    if: always()

    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.integration-tests.result }}" == "success" ]; then
            echo "✅ All integration tests passed!"
            exit 0
          else
            echo "❌ Some integration tests failed"
            exit 1
          fi
