name: Reindex Codebase RAG

on:
  push:
    branches: [master, main]
    paths:
      - 'src/**'
      - 'api/**'
      - 'scripts/**'
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2am UTC

jobs:
  reindex:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-rag.txt
      
      - name: Run indexer
        env:
          VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
        run: |
          python src/rag/indexing/code_indexer.py
      
      - name: Upload vector database
        uses: actions/upload-artifact@v4
        with:
          name: vector-db-${{ github.sha }}
          path: ./data/vector_db
          retention-days: 90
      
      - name: Notify on success
        if: success()
        run: |
          echo "✅ RAG indexing completed successfully"
          echo "Vector database available as artifact: vector-db-${{ github.sha }}"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ RAG indexing failed"
          echo "Check logs for details"
