name: Workflow Automation Platform Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/workflow-automation-platforms.yml'

jobs:
  platform-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: n8n
            setup: |
              sudo apt-get update -y || true
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs docker.io
              npm i -g pnpm
              docker pull n8nio/n8n:latest
            test: |
              docker run --rm n8nio/n8n:latest --version || true
          - name: activepieces
            setup: |
              sudo apt-get update -y || true
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
              npm i -g @activepieces/cli
            test: |
              ap --version || npx @activepieces/cli --version
          - name: huginn
            setup: |
              sudo apt-get update -y || true
              sudo apt-get install -y docker.io
              docker pull ghcr.io/huginn/huginn:latest
            test: |
              docker run --rm ghcr.io/huginn/huginn:latest bash -lc 'ruby -v' || true
          - name: automatiko
            setup: |
              sudo apt-get update -y || true
              sudo apt-get install -y default-jre
            test: |
              java -version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup platform
        shell: bash
        run: ${{ matrix.platform.setup }}

      - name: Run smoke test
        shell: bash
        run: ${{ matrix.platform.test }}

  summary:
    needs: platform-tests
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo '# ✅ Workflow automation platforms smoke tests completed' >> $GITHUB_STEP_SUMMARY
